[package]
name = "warp-packer"
version = "0.1.1"
authors = ["Diego Giagio <diego@giagio.com>"]

[dependencies]
clap = "2.32.0"
dirs = "1.0.4"
reqwest = "0.9.2"
tempdir = "0.3.7"
flate2 = "1.0"
tar = "0.4"
